### PR TITLE
Added linting instructions to README

### PR DESCRIPTION
**Pull request by sgnn7**
Added instructions for linting files in the repository.

### CODE REVIEW

**Comment by manuq** [comment]
@sgnn7 two questions:

- Are we asking contributors to pass both checks, jshint and eslint?
- Besides checking a single file, is there a shortcut to make sure all the source code passes?

**Comment by sgnn7** [comment]
@manuq I think we need to figure out which to use and run with it but as of now, both have configurations in the codebase. The shortcut to check all files would probably be `eslint .` in `lib/` or `jshint .` in root of project.

**Comment by manuq** [comment]
@sgnn7 sounds good, let's merge this for now, but deprecate one of them to avoid one more requirement for potential contributors.

**Comment by sgnn7** [comment]
@manuq Sounds good

**Pull request merged**
